Revert "ci: replace setuptools_scm write_to with version_file"
To maintain Python 3.7 compatibility, revert the version file location reference back to
`write_to` under the `tool.setuptools_scm` section. Without doing so, the Python 3.7
test job fails with an error like the following:

```
          return cls(relative_to=name, **args)
      TypeError: __init__() got an unexpected keyword argument 'version_file'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

This reverts commit bd1ce1468e37e4b148b65f8c1142d4cc0fcd3bbf.