Revert "ci: pin setuptools_scm>=8 from vendor docs"
To maintain Python 3.7 compatibility, remove the `>=8` requirement. Without doing so,
the Python 3.7 test job fails with an error like the following:

```
ERROR: Could not find a version that satisfies the requirement setuptools_scm>=8 (from versions: 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 1.10.0, 1.10.1, 1.11.0, 1.11.1, 1.13.0, 1.13.1, 1.14.0rc1, 1.14.0, 1.15.0rc1, 1.15.0, 1.15.1rc1, 1.15.4, 1.15.5, 1.15.6, 1.15.7, 1.16.0, 1.16.1, 1.16.2, 1.17.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.0.2, 3.0.4, 3.0.5, 3.0.6, 3.1.0, 3.2.0, 3.3.1, 3.3.2, 3.3.3, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.5.0, 4.0.0, 4.1.0, 4.1.1, 4.1.2, 5.0.0, 5.0.1, 5.0.2, 6.0.0, 6.0.1, 6.3.1, 6.3.2, 6.4.0, 6.4.1, 6.4.2, 7.0.1, 7.0.2, 7.0.3, 7.0.4, 7.0.5, 7.1.0)
ERROR: No matching distribution found for setuptools_scm>=8
[end of output]
```

This reverts commit c50c360169d3392d7c201685c06d0081ee8dbd79.